// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package oneuptime

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SmsLogResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Description:         "The description of the resource",
				MarkdownDescription: "The description of the resource",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier",
				MarkdownDescription: "The unique identifier",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the resource",
				MarkdownDescription: "The name of the resource",
			},
			"select": schema.StringAttribute{
				Optional:            true,
				Description:         "The select field",
				MarkdownDescription: "The select field",
			},
		},
	}
}

type SmsLogModel struct {
	Description types.String `tfsdk:"description"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Select      types.String `tfsdk:"select"`
}
