package provider

import (
    "context"
    "encoding/json"
    "fmt"
    "net/http"
    "math/big"

    "github.com/hashicorp/terraform-plugin-framework/datasource"
    "github.com/hashicorp/terraform-plugin-framework/datasource/schema"
    "github.com/hashicorp/terraform-plugin-framework/types"
    "github.com/hashicorp/terraform-plugin-log/tflog"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &StatusPageDomainDataSource{}

func NewStatusPageDomainDataSource() datasource.DataSource {
    return &StatusPageDomainDataSource{}
}

// StatusPageDomainDataSource defines the data source implementation.
type StatusPageDomainDataSource struct {
    client *Client
}

// StatusPageDomainDataSourceModel describes the data source data model.
type StatusPageDomainDataSourceModel struct {
    Id types.String `tfsdk:"id"`
    Name types.String `tfsdk:"name"`
    CreatedAt types.String `tfsdk:"created_at"`
    UpdatedAt types.String `tfsdk:"updated_at"`
    DeletedAt types.String `tfsdk:"deleted_at"`
    Version types.Number `tfsdk:"version"`
    ProjectId types.String `tfsdk:"project_id"`
    DomainId types.String `tfsdk:"domain_id"`
    StatusPageId types.String `tfsdk:"status_page_id"`
    Subdomain types.String `tfsdk:"subdomain"`
    FullDomain types.String `tfsdk:"full_domain"`
    CreatedByUserId types.String `tfsdk:"created_by_user_id"`
    IsCnameVerified types.Bool `tfsdk:"is_cname_verified"`
    IsSslOrdered types.Bool `tfsdk:"is_ssl_ordered"`
    IsSslProvisioned types.Bool `tfsdk:"is_ssl_provisioned"`
    CustomCertificate types.String `tfsdk:"custom_certificate"`
    CustomCertificateKey types.String `tfsdk:"custom_certificate_key"`
    IsCustomCertificate types.Bool `tfsdk:"is_custom_certificate"`
    CertificateReissueRequestedAt types.String `tfsdk:"certificate_reissue_requested_at"`
}

func (d *StatusPageDomainDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
    resp.TypeName = req.ProviderTypeName + "_status_page_domain"
}

func (d *StatusPageDomainDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
    resp.Schema = schema.Schema{
        MarkdownDescription: "Manage custom domains for your status page Look up an existing status_page_domain by `id` or by `name`.",

        Attributes: map[string]schema.Attribute{
            "id": schema.StringAttribute{
                MarkdownDescription: "Look up by unique identifier. Exactly one of `id` or `name` must be set.",
                Optional: true,
                Computed: true,
            },
            "name": schema.StringAttribute{
                MarkdownDescription: "Look up by name. Exactly one of `id` or `name` must be set. Fails if the name does not match exactly one item.",
                Optional: true,
                Computed: true,
            },
            "created_at": schema.StringAttribute{
                MarkdownDescription: "A date time object.",
                Computed: true,
            },
            "updated_at": schema.StringAttribute{
                MarkdownDescription: "A date time object.",
                Computed: true,
            },
            "deleted_at": schema.StringAttribute{
                MarkdownDescription: "A date time object.",
                Computed: true,
            },
            "version": schema.NumberAttribute{
                MarkdownDescription: "Object version",
                Computed: true,
            },
            "project_id": schema.StringAttribute{
                MarkdownDescription: "A unique identifier for an object, represented as a UUID.",
                Computed: true,
            },
            "domain_id": schema.StringAttribute{
                MarkdownDescription: "A unique identifier for an object, represented as a UUID.",
                Computed: true,
            },
            "status_page_id": schema.StringAttribute{
                MarkdownDescription: "A unique identifier for an object, represented as a UUID.",
                Computed: true,
            },
            "subdomain": schema.StringAttribute{
                MarkdownDescription: "Subdomain label for your status page such as 'status'. Leave blank or enter @ to use the root domain..",
                Computed: true,
            },
            "full_domain": schema.StringAttribute{
                MarkdownDescription: "Full domain of your status page (like status.acmeinc.com). This is autogenerated and is derived from subdomain and domain..",
                Computed: true,
            },
            "created_by_user_id": schema.StringAttribute{
                MarkdownDescription: "A unique identifier for an object, represented as a UUID.",
                Computed: true,
            },
            "is_cname_verified": schema.BoolAttribute{
                MarkdownDescription: "Is CNAME Verified?.",
                Computed: true,
            },
            "is_ssl_ordered": schema.BoolAttribute{
                MarkdownDescription: "Is SSL ordered?.",
                Computed: true,
            },
            "is_ssl_provisioned": schema.BoolAttribute{
                MarkdownDescription: "Is SSL provisioned?.",
                Computed: true,
            },
            "custom_certificate": schema.StringAttribute{
                Computed: true,
            },
            "custom_certificate_key": schema.StringAttribute{
                Computed: true,
            },
            "is_custom_certificate": schema.BoolAttribute{
                Computed: true,
            },
            "certificate_reissue_requested_at": schema.StringAttribute{
                MarkdownDescription: "A date time object.",
                Computed: true,
            },
        },
    }
}

func (d *StatusPageDomainDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
    // Prevent panic if the provider has not been configured.
    if req.ProviderData == nil {
        return
    }

    client, ok := req.ProviderData.(*Client)

    if !ok {
        resp.Diagnostics.AddError(
            "Unexpected Data Source Configure Type",
            fmt.Sprintf("Expected *Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
        )

        return
    }

    d.client = client
}

func (d *StatusPageDomainDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
    var data StatusPageDomainDataSourceModel

    // Read Terraform configuration data into the model
    resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

    if resp.Diagnostics.HasError() {
        return
    }

    hasId := !data.Id.IsNull() && data.Id.ValueString() != ""
    hasName := !data.Name.IsNull() && data.Name.ValueString() != ""
    if hasId == hasName {
        resp.Diagnostics.AddError(
            "Invalid Lookup",
            "Exactly one of `id` or `name` must be set to look up a status_page_domain.",
        )
        return
    }

    selectParam := map[string]interface{}{
        "name": true,
        "createdAt": true,
        "updatedAt": true,
        "deletedAt": true,
        "version": true,
        "projectId": true,
        "domainId": true,
        "statusPageId": true,
        "subdomain": true,
        "fullDomain": true,
        "createdByUserId": true,
        "isCnameVerified": true,
        "isSslOrdered": true,
        "isSslProvisioned": true,
        "customCertificate": true,
        "customCertificateKey": true,
        "isCustomCertificate": true,
        "certificateReissueRequestedAt": true,
        "_id": true,
    }

    var item map[string]interface{}
    if hasId {
        readPath := "/status-page-domain/" + data.Id.ValueString() + "/get-item"
        httpResp, err := d.client.PostWithSelect(ctx, readPath, selectParam)
        if err != nil {
            resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read status_page_domain, got error: %s", err))
            return
        }
        if httpResp.StatusCode == http.StatusNotFound {
            resp.Diagnostics.AddError("Not Found", fmt.Sprintf("No status_page_domain found with id %q.", data.Id.ValueString()))
            return
        }
        var itemResponse map[string]interface{}
        if err := d.client.ParseResponse(httpResp, &itemResponse); err != nil {
            resp.Diagnostics.AddError("OneUptime API Error", fmt.Sprintf("Unable to read status_page_domain: %s", err))
            return
        }
        if wrapper, ok := itemResponse["data"].(map[string]interface{}); ok {
            item = wrapper
        } else {
            item = itemResponse
        }
    } else {
        listBody := map[string]interface{}{
            "query": map[string]interface{}{
                "name": data.Name.ValueString(),
            },
            "select": selectParam,
            // limit 2 is enough to detect ambiguity without paging.
            "limit": 2,
        }
        httpResp, err := d.client.PostBodyWithSelect(ctx, "/status-page-domain/get-list", listBody)
        if err != nil {
            resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to list status_page_domain, got error: %s", err))
            return
        }
        var listResponse map[string]interface{}
        if err := d.client.ParseResponse(httpResp, &listResponse); err != nil {
            resp.Diagnostics.AddError("OneUptime API Error", fmt.Sprintf("Unable to list status_page_domain: %s", err))
            return
        }
        items, _ := listResponse["data"].([]interface{})
        if len(items) == 0 {
            resp.Diagnostics.AddError("Not Found", fmt.Sprintf("No status_page_domain found with name %q.", data.Name.ValueString()))
            return
        }
        if len(items) > 1 {
            resp.Diagnostics.AddError("Ambiguous Match", fmt.Sprintf("More than one status_page_domain matches name %q. Use the id attribute to disambiguate.", data.Name.ValueString()))
            return
        }
        first, ok := items[0].(map[string]interface{})
        if !ok {
            resp.Diagnostics.AddError("OneUptime API Error", "Unexpected list response shape for status_page_domain.")
            return
        }
        item = first
    }

    // Update the model with response data
    if obj, ok := item["_id"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.Id = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.Id = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.Id = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.Id = types.StringValue(string(jsonBytes))
        } else {
            data.Id = types.StringNull()
        }
    } else if val, ok := item["_id"].(string); ok {
        data.Id = types.StringValue(val)
    } else {
        data.Id = types.StringNull()
    }
    if obj, ok := item["name"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.Name = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.Name = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.Name = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.Name = types.StringValue(string(jsonBytes))
        } else {
            data.Name = types.StringNull()
        }
    } else if val, ok := item["name"].(string); ok {
        data.Name = types.StringValue(val)
    } else {
        data.Name = types.StringNull()
    }
    if obj, ok := item["createdAt"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.CreatedAt = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.CreatedAt = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.CreatedAt = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.CreatedAt = types.StringValue(string(jsonBytes))
        } else {
            data.CreatedAt = types.StringNull()
        }
    } else if val, ok := item["createdAt"].(string); ok {
        data.CreatedAt = types.StringValue(val)
    } else {
        data.CreatedAt = types.StringNull()
    }
    if obj, ok := item["updatedAt"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.UpdatedAt = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.UpdatedAt = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.UpdatedAt = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.UpdatedAt = types.StringValue(string(jsonBytes))
        } else {
            data.UpdatedAt = types.StringNull()
        }
    } else if val, ok := item["updatedAt"].(string); ok {
        data.UpdatedAt = types.StringValue(val)
    } else {
        data.UpdatedAt = types.StringNull()
    }
    if obj, ok := item["deletedAt"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.DeletedAt = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.DeletedAt = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.DeletedAt = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.DeletedAt = types.StringValue(string(jsonBytes))
        } else {
            data.DeletedAt = types.StringNull()
        }
    } else if val, ok := item["deletedAt"].(string); ok {
        data.DeletedAt = types.StringValue(val)
    } else {
        data.DeletedAt = types.StringNull()
    }
    if val, ok := item["version"].(float64); ok {
        data.Version = types.NumberValue(big.NewFloat(val))
    } else if obj, ok := item["version"].(map[string]interface{}); ok {
        if val, ok := obj["value"].(float64); ok {
            data.Version = types.NumberValue(big.NewFloat(val))
        } else {
            data.Version = types.NumberNull()
        }
    } else {
        data.Version = types.NumberNull()
    }
    if obj, ok := item["projectId"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.ProjectId = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.ProjectId = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.ProjectId = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.ProjectId = types.StringValue(string(jsonBytes))
        } else {
            data.ProjectId = types.StringNull()
        }
    } else if val, ok := item["projectId"].(string); ok {
        data.ProjectId = types.StringValue(val)
    } else {
        data.ProjectId = types.StringNull()
    }
    if obj, ok := item["domainId"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.DomainId = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.DomainId = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.DomainId = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.DomainId = types.StringValue(string(jsonBytes))
        } else {
            data.DomainId = types.StringNull()
        }
    } else if val, ok := item["domainId"].(string); ok {
        data.DomainId = types.StringValue(val)
    } else {
        data.DomainId = types.StringNull()
    }
    if obj, ok := item["statusPageId"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.StatusPageId = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.StatusPageId = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.StatusPageId = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.StatusPageId = types.StringValue(string(jsonBytes))
        } else {
            data.StatusPageId = types.StringNull()
        }
    } else if val, ok := item["statusPageId"].(string); ok {
        data.StatusPageId = types.StringValue(val)
    } else {
        data.StatusPageId = types.StringNull()
    }
    if obj, ok := item["subdomain"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.Subdomain = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.Subdomain = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.Subdomain = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.Subdomain = types.StringValue(string(jsonBytes))
        } else {
            data.Subdomain = types.StringNull()
        }
    } else if val, ok := item["subdomain"].(string); ok {
        data.Subdomain = types.StringValue(val)
    } else {
        data.Subdomain = types.StringNull()
    }
    if obj, ok := item["fullDomain"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.FullDomain = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.FullDomain = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.FullDomain = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.FullDomain = types.StringValue(string(jsonBytes))
        } else {
            data.FullDomain = types.StringNull()
        }
    } else if val, ok := item["fullDomain"].(string); ok {
        data.FullDomain = types.StringValue(val)
    } else {
        data.FullDomain = types.StringNull()
    }
    if obj, ok := item["createdByUserId"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.CreatedByUserId = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.CreatedByUserId = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.CreatedByUserId = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.CreatedByUserId = types.StringValue(string(jsonBytes))
        } else {
            data.CreatedByUserId = types.StringNull()
        }
    } else if val, ok := item["createdByUserId"].(string); ok {
        data.CreatedByUserId = types.StringValue(val)
    } else {
        data.CreatedByUserId = types.StringNull()
    }
    if val, ok := item["isCnameVerified"].(bool); ok {
        data.IsCnameVerified = types.BoolValue(val)
    } else {
        data.IsCnameVerified = types.BoolNull()
    }
    if val, ok := item["isSslOrdered"].(bool); ok {
        data.IsSslOrdered = types.BoolValue(val)
    } else {
        data.IsSslOrdered = types.BoolNull()
    }
    if val, ok := item["isSslProvisioned"].(bool); ok {
        data.IsSslProvisioned = types.BoolValue(val)
    } else {
        data.IsSslProvisioned = types.BoolNull()
    }
    if obj, ok := item["customCertificate"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.CustomCertificate = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.CustomCertificate = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.CustomCertificate = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.CustomCertificate = types.StringValue(string(jsonBytes))
        } else {
            data.CustomCertificate = types.StringNull()
        }
    } else if val, ok := item["customCertificate"].(string); ok {
        data.CustomCertificate = types.StringValue(val)
    } else {
        data.CustomCertificate = types.StringNull()
    }
    if obj, ok := item["customCertificateKey"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.CustomCertificateKey = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.CustomCertificateKey = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.CustomCertificateKey = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.CustomCertificateKey = types.StringValue(string(jsonBytes))
        } else {
            data.CustomCertificateKey = types.StringNull()
        }
    } else if val, ok := item["customCertificateKey"].(string); ok {
        data.CustomCertificateKey = types.StringValue(val)
    } else {
        data.CustomCertificateKey = types.StringNull()
    }
    if val, ok := item["isCustomCertificate"].(bool); ok {
        data.IsCustomCertificate = types.BoolValue(val)
    } else {
        data.IsCustomCertificate = types.BoolNull()
    }
    if obj, ok := item["certificateReissueRequestedAt"].(map[string]interface{}); ok {
        if val, ok := obj["_id"].(string); ok && val != "" {
            data.CertificateReissueRequestedAt = types.StringValue(val)
        } else if val, ok := obj["value"].(string); ok {
            data.CertificateReissueRequestedAt = types.StringValue(val)
        } else if val, ok := obj["value"].(float64); ok {
            data.CertificateReissueRequestedAt = types.StringValue(fmt.Sprintf("%v", val))
        } else if jsonBytes, err := json.Marshal(obj); err == nil {
            data.CertificateReissueRequestedAt = types.StringValue(string(jsonBytes))
        } else {
            data.CertificateReissueRequestedAt = types.StringNull()
        }
    } else if val, ok := item["certificateReissueRequestedAt"].(string); ok {
        data.CertificateReissueRequestedAt = types.StringValue(val)
    } else {
        data.CertificateReissueRequestedAt = types.StringNull()
    }

    // Write logs using the tflog package
    tflog.Trace(ctx, "read a data source")

    // Save data into Terraform state
    resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
